.github/workflows/cmake-multi-platform.yml, .gitignore, CMakeLists.txt, cmake/FetchEigen/CMakeLists.txt, cmake/FetchTaskflow/CMakeLists.txt
This pull request refactors the three CMakeLists.txt and the cmake-multi-platform.yml workflow file. Many of the changes are purely aesthetic, including:
- Added comments to better explain what's going on in the files
- Fixed the spacing to conform to the (seemingly) project convention of `1 indent = 4 spaces`.
However, there are other small changes that are functional. I won't explain them in detail, unless anyone is interested.
Changes have been tested by completing a workflow run on the feature branch.
=> Refactor CMakeLists and Actions workflow

CONTRIBUTING.md, src/CMakeLists.txt
This pull request updates the CONTRIBUTING.md file to describe an ideal workflow for submitting pull requests to the main repository.
=> [Doc] Update CONTRIBUTING.md with a Pull Request workflow

src/Add.cpp, src/Exponent.cpp, src/Subtract.cpp, tests/AddTests.cpp, tests/ExponentTests.cpp, tests/MultiplyTests.cpp, tests/SubtractTests.cpp
Added more tests for additional cases of creating imaginary and other operations.
=> More Imaginary Tests

.github/workflows/clang-format.yml, include/Oasis/Add.hpp, include/Oasis/BinaryExpression.hpp, include/Oasis/Divide.hpp, include/Oasis/Exponent.hpp, include/Oasis/Expression.hpp, include/Oasis/Log.hpp, include/Oasis/Multiply.hpp, include/Oasis/Subtract.hpp, src/Multiply.cpp, src/Subtract.cpp, src/Variable.cpp
This PR adds a workflow for checking whether code is formatted to the repo's standards and to apply the formatting the codebase if needed.
=> [Workflow] Add GitHub Actions workflow to run clang-format

include/Oasis/BinaryExpression.hpp, include/Oasis/Expression.hpp, src/Divide.cpp
This pull request runs the clang-format workflow added in #33.
=> [Workflow] Run clang-format workflow

.github/workflows/clang-format.yml, .github/workflows/cmake-multi-platform.yml, .github/workflows/doxygen.yml, .github/workflows/format-cmake.yml
This pull request makes several small changes to our GitHub Actions workflows to ensure consistency.
=> [Workflow] Make small changes to workflows

.github/workflows/code-coverage-comment.yml
This pull request fixes `code-coverage-comment.yml` in multiple ways.
* Some typos are fixed to make this file a valid workflow.
* The `unzip` call is fixed to escape the wilcard.
* The contents of the coverage report is now wrapped correctly in backticks.
=> [Bugfix] Fix code-coverage-comment.yml

.github/workflows/clang-format.yml, include/Oasis/Add.hpp
This addresses #50 by using ClangFormat's built in means of checking whether files need to be changed.
=> Simplify ClangFormat Workflow

src/Add.cpp
This PR removes some redundant cases in `Add`.
=> Remove Redundant Add Cases

src/Add.cpp
Remove more redundant cases in `Add`
=> Removed two imaginary cases

.github/workflows/doxygen.yml, Doxyfile
=> Use Graphviz to generate SVG graphs

.github/workflows/doxygen.yml
This PR updates the Doxygen version used by the GitHub Runner and also the actions used by the runner to push to GitHub Pages.
=> Update Doxygen and GitHub Actions

.github/workflows/code-coverage.yml, CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
The current results from implementation in the workflow is not consistent with coverage results from a local environment. This PR remedies that. Addresses #49
=> [Workflow] Fix Code Coverage

CONTRIBUTING.md
See title. Most notably this elaborates on the code style guidelines.
=> [Documentation] Update CONTRIBUTING.md

.github/workflows/cmake-multi-platform.yml, .github/workflows/valgrind.yml
- Enables GCC and Debug builds
- Adds testing with Valgrind
=> [Workflow] Add GCC and Debug Builds and Valgrind Checks

extras/src/FromString.cpp, extras/src/InFixSerializer.cpp, extras/src/MathMLSerializer.cpp
This PR adds support for parsing integrals and fix some syntax issues with serializing integrals.
=> [Feature] Parse Integral and Integral Serialization Fixes

extras/include/Oasis/MathMLSerializer.hpp, extras/src/MathMLSerializer.cpp, extras/tests/MathMLTests.cpp, include/Oasis/Expression.hpp, include/Oasis/Matrix.hpp, include/Oasis/Serialization.hpp, src/Add.cpp, src/CMakeLists.txt, src/Matrix.cpp, src/Multiply.cpp, src/Subtract.cpp, tests/CMakeLists.txt, tests/LogTests.cpp, tests/MatrixTests.cpp
Created and added a node for Matrices to be used in Oasis. Added primary matrix operations for Inverse, Transpose, Multiplication, and multiplication by a scalar.
=> Added matrix nodes

extras/include/Oasis/FromString.hpp, extras/src/FromString.cpp, extras/tests/InFixTests.cpp
This PR separated the prepreprocessng into multiple passses. Specifically, this PR addresses the issue whereby $3x^2$ would be interpreted as $(3x)^2$ as opposed to $3\*(x^2)$.
=> Improve preprocessor

.github/workflows/code-coverage-comment.yml
This pull request includes updates to the `.github/workflows/code-coverage-comment.yml` file to improve the code quality and compatibility with the latest GitHub Actions.
Updates to GitHub Actions:
* Updated `actions/github-script` from version 6 to version 7 for better compatibility and new features. (`.github/workflows/code-coverage-comment.yml`)
* Changed variable declarations from `let` to `const` for better code practices and immutability. (`.github/workflows/code-coverage-comment.yml`)
* Replaced `.filter()` with `.find()` for more efficient artifact matching. (`.github/workflows/code-coverage-comment.yml`)
* Updated artifact names to match the new naming conventions. (`.github/workflows/code-coverage-comment.yml`)
* Used `process.env.GITHUB_WORKSPACE` instead of …
=> Fix Code Coverage Comment Workflow Action

src/Exponent.cpp, tests/DifferentiateTests.cpp
Added check for same base variable as differentiation variable when taking the derivative of exponent with variable^expression.
Also, added general differentiation of exponent functions (expression^expression)
Added 3 Test cases
Fixes Issue #146
=> Fix and updated exponent derivatives

README.md
This pull request updates the `README` file to provide detailed setup and usage instructions for OASIS. It includes:
- Expanded introduction to OASIS and its features.  
- Comprehensive build instructions using CMake.  
- Example code for application integration.  
- Contribution guidelines to assist new contributors.  
This update is intended to enhance accessibility and streamline the setup process
=> Update README with setup, usage, and contribution guidelines
