open-algebra/Oasis

CMakeLists.txt, tests/CMakeLists.txt
In #17, building the unit test executable was moved to a subdirectory of the project root. This inadvertently messed up CTest, especially its integration with IDEs like Visual Studio. Specifically, the `include(CTest)` statement must be present in the top-level `CMakeLists.txt`, so that it can invoke `enable_testing()`. This pull request fixes this issue.
=> [Bugfix] Fix CTest integration in IDEs

src/Exponent.cpp
Fixed build warning. Closes #23.
=> [Bugfix] replace abs with std::abs

.github/workflows/cmake-multi-platform.yml
This pull request updates `cmake-multi-platform.yml` to upload artifacts to GitHub. In the case where a build fails, it may be useful for contributors to see the contents of the `build` directory. Uploading this directory now makes that possible without having to run it again locally.
=> [Workflow] Leave build artifacts during workflow runs

.github/workflows/cmake-multi-platform.yml
The current CI process takes an excessive amount of time to run due to it currently building all targets. This PR aims to improve CI runtimes by explicitly specifying targets to build. Namely, it builds the Oasis target first so that compile-time errors in the library can be caught early.
=> [Workflow] Expedite building Oasis in the build and test workflow

CMakeLists.txt, include/Oasis/BinaryExpression.hpp, include/Oasis/LeafExpression.hpp, src/Add.cpp, src/CMakeLists.txt, src/Divide.cpp, src/Exponent.cpp, src/Imaginary.cpp, src/Multiply.cpp, src/Real.cpp, src/Subtract.cpp, src/Variable.cpp, tests/BinaryExpressionTests.cpp, tests/CMakeLists.txt
This pull request updates our build and test workflow to compile with as many practical warning flags as possible. For MSVC, this includes `/W3` and `/WX`. For all other compilers, this includes `-Wall`, `-Wextra`, `-Wpedantic`, and `-Werror`.
Files have also been modified to fix any new warnings emitted. Three classes of warnings have been patched:
* **Unused parameters:** in many instances, `tf::Subflow` was not being used, causing recursive calls to not be parallelized. This occurs elsewhere in the code, and has thus not been fixed. Rather, the warnings are suppressed by excluding the parameter name.
* **Different signedness:** trivial change from `int` to `unsigned int` (should really be `size_type`).
* **Unused variable:** in `Exponent.cpp`, there is an unused variable that may or …
=> [Workflow] Treat all warnings as errors

.github/workflows/doxygen.yml
This pull request fixes the GitHub Pages deployment workflow broken by #35.
=> [Workflow] Fix Doxygen workflow

include/Oasis/BinaryExpression.hpp, include/Oasis/Expression.hpp, tests/BinaryExpressionTests.cpp
The previous implementation of `Equals` would consider the following expression, $(1+2)+3$, not equal to $(2+3)+1$. This PR makes so that `Equals` does consider the two expressions equal without simplifying.
=> [Feature] Made Equals work for Associative and Commutative Expressions.

include/Oasis/BinaryExpression.hpp
This PR aims to add a number of improvements to BinaryExpression, namely:
- Parallelized `Copy()`
- Made `Specialize` more readable (and possibly more performant)
- Added overloads for `SetMostSigOp()` and `SetLeastSigOp()`. Specifically, it add overloads that accepts rvalues of `std::unique_ptr` to `Expression`s. This makes it so that calls to `Copy()` explicitly happen at the call site, and the resulting `unique_ptr` is moved into the `BinaryExpression` avoiding redundant copies.
- Made `SwapOperands` `const`
- Optimized `BuildFromVector`. Previously, `BuildFromVector` was implemented recursively where each recursive call maintained its own copy of the set of original expressions. This new implementation is iterative, and only maintains one copy of set the original expressions.
=> [Feature] Improve BinaryExpression Functions

tests/CMakeLists.txt
This pull request changes the `CMakeLists.txt` for the unit tests to use `/bigobj`. As found on multiple Windows systems, the `ExponentTests.cpp` generates fatal error [C1128](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128).
Our chosen fix is to use the `/bigobj` compiler flag for all unit test files.
=> [Bugfix[ Compile tests on Windows with /bigobj

CMakeLists.txt
This PR reduces the minimum CMake Required from 3.26 to 3.18 (The minimum imposed by Taskflow).
=> Downgrade CMake

src/CMakeLists.txt
See title. Some builds on Windows may fail due to exceeding the default section limits
=> [Workflow] Enabled `/bigobj` flag for Windows builds

.github/workflows/code-coverage-comment.yml, .github/workflows/code-coverage.yml
This reverts commit 834ea90ae8793e47ec3e161fd30d4faad598709e. #75 broke the ability for code coverage reports to be commented on PRs opened from forks of this repo. This PR reverts that which should fix it.
=> [Workflow] Fix Code Coverage Reports for PRs opened from forks

include/Oasis/Add.hpp, include/Oasis/Expression.hpp, include/Oasis/Negate.hpp, include/Oasis/UnaryExpression.hpp, src/CMakeLists.txt, src/Negate.cpp, tests/CMakeLists.txt, tests/NegateTests.cpp
This PR adds UnaryExpression. An abstract node for expressions with a single operand such as negation, square roots, etc.
This PR also adds the `Negate` node, a convenience node to make tree insertion and balancing easier, for instance dealing with `Add`. This addresses #12.
=> [Feature] Add `UnaryExpression` and `Negate`

include/Oasis/Add.hpp, include/Oasis/BinaryExpression.hpp, include/Oasis/Multiply.hpp, src/Add.cpp, src/Divide.cpp, src/Multiply.cpp, tests/AddTests.cpp, tests/DivideTests.cpp, tests/MultiplyTests.cpp
This PR makes so that you don't have to nest arguments for associative and commutative expression like the example below:
```cpp
Multiply {
Real { 2.0 },
Multiply {
Variable { "x" },
Variable { "y" } } };
```
Now you can simply do:
```cpp
Multiply<> {
Real { 2.0 },
Variable { "x" },
Variable { "y" } };
```
Note type deduction for specialized expression fails when using this, thus it is only available for generalized expressions (hence the `<>`).
=> [Feature] Variadic Constructor Parameters

tests/DifferentiateTests.cpp, tests/IntegrateTests.cpp
Some derivative and integral tests had the same names which caused one or the other to be skipped. This has been rectified by giving each test a unique name,
=> Fix Calculus Tests

extras/include/Oasis/FromString.hpp, extras/src/FromString.cpp, extras/tests/InFixTests.cpp
This removes the old means of trying to parse an expression and catching an exception when it fails with the more tried and true methodology of returning errors as values.
=> Replaced exceptions with ParseResult

extras/src/FromString.cpp
Modified `processOp` and `processFunction` to return `false` instead of throwing exceptions on invalid argument counts. This ensures errors are passed up properly, and updated error messages to reflect changes.
=> [Bugfix] Remove `throws` from parsing

.github/workflows/format-cmake.yml
This pull request includes a change to the GitHub Actions workflow for formatting CMake files. The most important change is the switch to using a container for running `cmake-format` instead of installing `cmakelang` via `pip`.
Workflow improvements:
* [`.github/workflows/format-cmake.yml`](diffhunk://#diff-0bc3eeb3555e778720622da3b86be69cda7e3a7df5cc1d126f2d46b6831e79acR17-L26): Added a container (`cheshirekow/cmake-format`) to run `cmake-format`, removing the need to install `cmakelang` via `pip`.
=> Format CMakeLists.txt files using cmake-format

CMakeLists.txt, cmake/FetchBoost.cmake, include/CMakeLists.txt, include/Oasis/MatchCast.hpp, src/Add.cpp, src/CMakeLists.txt, src/Exponent.cpp
This pull request introduces the `MatchCast` utility and integrates Boost libraries into the project. The key changes involve adding the `MatchCast` header, updating CMake configurations to fetch and link Boost, and refactoring the `Exponent` class to use `MatchCast`.
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR40): Included `FetchBoost.cmake` to fetch Boost libraries.
* [`cmake/FetchBoost.cmake`](diffhunk://#diff-78f6dc9d41e80abf82d348c73abfd80426b371a004cb1581ee114a320ccffef8R1-R10): Added script to fetch and configure Boost library.
* [`src/CMakeLists.txt`](diffhunk://#diff-148715d6ea0c0ea0a346af3f6bd610d010d490eca35ac6a9b408748f7ca9e3f4L46-R46): Updated to link Boost::mpl library.
* …
=> [Feature] Introduce `MatchCast`

include/Oasis/Expression.hpp, include/Oasis/Negate.hpp
In this pull request, the ambiguity error with GCC is addressed by commenting out the method `Is()` in `Expression.hpp`. Additionally, `<cstdint>` is included for potential type usage, and a default parameter is added to `Negate` to improve flexibility and simplify usage.
=> Fix ambiguity error with GCC

.github/workflows/cmake-multi-platform.yml, .github/workflows/cmake-windows.yml, .gitignore
Introduced a new GitHub Actions workflow `cmake-windows.yml` to handle building and testing on Windows. Removed Valgrind installation and memory checks from the multi-platform workflow. Updated `.gitignore` to exclude JetBrains cache files.
=> [Feature] Run Linux workflow in a container and add Windows-specific build workflow

.github/workflows/cmake-linux.yml, .github/workflows/cmake-windows.yml
Upgraded actions/upload-artifact from version 3 to version 4 in GitHub workflows for both Linux and Windows. This ensures compatibility with the latest features and fixes provided by the updated action version.
=> Update upload-artifact action to version 4

CMakeLists.txt, io/include/Oasis/InFixSerializer.hpp, io/src/InFixSerializer.cpp, tests/AddTests.cpp, tests/CMakeLists.txt, tests/Common.hpp
This pull request includes the following changes:
- **Introduce OASIS_CAPTURE_WITH_SERIALIZER macro definition:** This macro provides an easy way to log the value of an expression in test cases.
- **Refactor serializer usage:** Introduced a global inline instance for streamlining usage of `OASIS_CAPTURE_WITH_SERIALIZER`. Simplified macro definition and removed redundant includes to enhance maintainability.
- **Reorganize test logic and enhance InFixSerializer:** Modularized test build configuration, introduced `Common.hpp` for shared test macros, and added support for new types (e.g., `Matrix`, `EulerNumber`, `Pi`, `Magnitude`) in `InFixSerializer`. Updated tests to align with enhanced serializer functionality.
=> Introduce `OASIS_CAPTURE_WITH_SERIALIZER`

src/Multiply.cpp, tests/DifferentiateTests.cpp, tests/MultiplyTests.cpp
Made it so that when multiplying a expression with a fraction it will combine into a single fraction
For example:
a*(1/x)
will become:
a/x
and similarly:
a/b * (c/d)
will become:
ac/(bd)
Also added new test case for this and changed existing test case to account for these changes.
Addresses issue #154
=> Multiplying fractions

src/Exponent.cpp, tests/DifferentiateTests.cpp
the section removed incorrectly assumes the exponent has no added constants
making it wrong for derivatives of functions like: x^(3x+2)
also removed associated test case, and changed name from generalBase to generalCase
Refixes issue #146 
fixes issue with pull request #149
=> Fixes mistake in pull request #149

CMakeLists.txt, cmake/FetchBoost.cmake, cmake/FetchEigen.cmake, include/CMakeLists.txt, include/Oasis/BinaryExpression.hpp, include/Oasis/Concepts.hpp, include/Oasis/Expression.hpp, include/Oasis/LeafExpression.hpp, include/Oasis/MatchCast.hpp, include/Oasis/UnaryExpression.hpp, include/Oasis/Visit.hpp, io/CMakeLists.txt, io/include/Oasis/FromString.hpp, io/include/Oasis/InFixSerializer.hpp, io/include/Oasis/MathMLSerializer.hpp, io/include/Oasis/TeXSerializer.hpp, io/src/FromString.cpp, io/src/InFixSerializer.cpp, io/src/MathMLSerializer.cpp, io/src/TeXSerializer.cpp, io/tests/InFixTests.cpp, io/tests/TeXTests.cpp, src/CMakeLists.txt, src/Exponent.cpp
This pull request introduces a series of improvements and updates:
- **`MatchCast` Refactoring**:
- Splits the `Case` into separate check and transformer lambdas for improved readability and maintainability.
- Adds stricter type compatibility validation between checks and transformers.
- **Boost Dependency Update**:
- Replaces custom `lambda_traits` with `Boost's callable_traits` to improve reliability and code cleanliness.
- **`consteval` Implementation**:
- Adds the `consteval` keyword to the `MatchCastImpl::Case` method, enforcing compile-time evaluation for safer, predictable code.
- **C++23 Standard Upgrade**:
- Updates the project to target C++23.
- Refactors error handling by replacing `std::variant` with `std::expected` in `FromString`.
- **Boost Any Replacement**:
- Substitutes …
=> Refactor `MatchCast` for type safety, C++23, and Boost enhancements

CMakeLists.txt, cli/CMakeLists.txt, cli/main.cpp, cmake/FetchLinenoise.cmake, include/Oasis/Concepts.hpp, include/Oasis/Expression.hpp, io/include/Oasis/FromString.hpp, io/include/Oasis/InFixSerializer.hpp, io/include/Oasis/MathMLSerializer.hpp, io/include/Oasis/TeXSerializer.hpp, io/src/FromString.cpp, io/src/InFixSerializer.cpp, io/src/TeXSerializer.cpp
This pull request introduces several significant changes to the build configuration and adds a new CLI executable. The most important changes include enabling the building of the CLI and IO components conditionally, adding dependencies for the CLI, and implementing the CLI's main functionality.
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR20-R23): Enabled `OASIS_BUILD_IO` when `OASIS_BUILD_CLI` is set, included `FetchTinyxml2.cmake` conditionally based on `OASIS_BUILD_IO`, and added dependencies for `OASIS_BUILD_CLI` including `FetchLinenoise.cmake` and `fmt` library. [[1]](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR20-R23) [[2]](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a …
=> [Feature] Command Line Interface

CMakeLists.txt, include/Oasis/MatchCast.hpp, io/CMakeLists.txt, io/include/Oasis/MathMLSerializer.hpp, src/CMakeLists.txt, src/Exponent.cpp, tests/ExponentTests.cpp
This pull request includes a series of updates aimed at improving the flexibility, readability, and robustness of `MatchCast` and `Exponent` visitors. Key changes made include:
- **Enhanced error management**: Introduced `std::expected` for error handling and adopted `gsl::not_null` to enforce non-null pointers across the logic.
- **Added visitor parameter**: Provided optional visitor support in `MatchCast` transformations, enabling external visitor instances for more adaptive handling.
- **Streamlined MatchCast Execute**: Removed the `fallback` parameter and refined logic to improve clarity and reduce redundancy in `MatchCast` and `Exponent`.
- **Improved concept flexibility**: Simplified `TransformerAcceptsCheckArg` by integrating `std::predicate` and refactoring the parameterization …
=> Improved GSL Integration

io/src/MathMLSerializer.cpp
Replaced the Unicode character for the integral symbol with its corresponding HTML entity ("&int;") to ensure compatibility with MathML parsers and improve readability in the output. This change aligns the serialization with standard MathML practices. Also happens to fix encoding issues with Embind
=> Use HTML entity for integral symbol in MathML output

cli/main.cpp
This pull request includes a small change to the `cli/main.cpp` file. The change improves the handling of the `result` variable in the `main` function by using an `if-else` statement to separately handle the success and error cases, which enhances code readability and correctness.
* [`cli/main.cpp`](diffhunk://#diff-75463708a4f8d57e41d9fbbacae91b7296d154c043da7f56ab78b21f8261052eL66-R68): Improved handling of `result` variable in the `main` function by using an `if-else` statement to separately handle success and error cases.
=> Correct result handling in CLI output formatting.
